### ISSUE TITLE
Modifying the ping message

### ISSUE THREAD

**Issue by Mikerah** [libp2p/js-libp2p-ping#76]
Currently, upon a successful connection, a peer sends a `ping` message to a peer that it wants to connect to. Would it be possible to send any arbitrary message upon a successful handshake other than a `ping`?

**Comment by jacobheun** [comment]
> Currently, upon a successful connection, a peer sends a ping message to a peer that it wants to connect to.

This isn't automatic when a peer connects. `libp2p-ping` ships with `libp2p` but nothing is triggering it atm.

> Would it be possible to send any arbitrary message upon a successful handshake other than a ping?

Are you talking about changing what `libp2p-ping` itself sends? Right now it sends 32 random bytes and expects those to be echoed back, so even if you changed it, it would be restricted to exactly 32 bytes.

If you want to have more flexibility/control about what you're sending, you should look at creating another protocol for that.

Is there something more specific you're trying to achieve?

**Comment by Mikerah** [comment]
What I'm trying to achieve is upon a connection, both peers involved in the handshake send a specific `Hello` message.

**Comment by jacobheun** [comment]
Here's a basic (untested) example of how that might be done. The reason to use a new protocol is because you're defining a schema for the data you want to exchange. It's similar to an api, where the protocols can be considered endpoints. If the underlying data needs to be changed the protocol / protocol version should also change.

```js
const HELLO_PROTOCOL = '/hello/1.0.0'
const helloHandler = (protocol, conn) => {
  pull(
    pull.values([Buffer.from('hello')]),
    conn,
    pull.collect((values) => {
     // The peers response
      console.log(values) // [Buffer.from('hello')]
    })
  )
}
const sayHello = (peerInfo) => {
  libp2p.dialProtocol(peerInfo, HELLO_PROTOCOL,  (err, conn) => {
    pull(
      pull.values([Buffer.from('hello')]),
      conn,
      pull.collect((values) => {
        // The peers response
        console.log(values) // [Buffer.from('hello')]
      })
    )
  })
}

// Setup the handler for when peers try to say hello
libp2p.handle(HELLO_PROTOCOL, helloHandler)
// Say hello whenever a peer connects
libp2p.on('peer:connect', sayHello)
```

**Comment by Mikerah** [comment]
I'll try this for now. Thanks
